//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuDiretoService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"select
	lpad( pcprodut.codprod , 6, '0') CODPROD, 
	pcprodut.descricao,
	pcprodut.embalagem,
	(select pcdepto.descricao from pcdepto where pcdepto.codepto =  pcprodut.codepto) categoria , 
      pcprodut.pesobruto,
               TRUNC((pcest.qtestger - ( pcest.qtreserv + pcest.qtbloqueada)) ,0)  estoque ,
	TRUNC(nvl( PCTABPR.pvenda,0),2)  PRECO,
	PCPRODUT.embalagem,
	pcprodut.nbm,
	PCPRODUT.codauxiliar ean,
	pcprodut.codauxiliar2 dun,
	case when  PCPRODUT.obs2 = 'FL' then 'D' ELSE 'A' END status,
	greatest(PCPRODUT.dtultalter, PCTABPR.dtultaltpvenda, PCEST.DTULTALTERSRVPRC) ULTIMA_MOVIMENTACAO 

from 
	pcprodut, pcest , PCTABPR
where
	PCEST.codprod = PCPRODUT.CODPROD
	AND PCPRODUT.codprod = PCTABPR.codprod
	AND PCEST.codfilial  IN (:CODFILIAL)
	AND PCPRODUT.CODEPTO IN  (12,14,40,70,71,55,42,64,63) /*DEPARTAMENTOS ELEGÍVEIS PARA VENDAS  (12,14,40,70,71,55,42,64,63)*/

	AND PCTABPR.numregiao IN(:REGIAO)

	AND greatest(PCPRODUT.dtultalter, PCTABPR.dtultaltpvenda, PCEST.DTULTALTERSRVPRC) >= to_date(:DTULTALT,'dd/mm/yyyy hh24:mi:ss')
")]
        public string query_colecao_produtos {
            get {
                return ((string)(this["query_colecao_produtos"]));
            }
        }
    }
}
